insert into public.categories (label, slug, icon_name, sort_order, is_active)
values
  ('Makanan', 'makanan', 'restaurant_outlined', 1, true),
  ('Minuman', 'minuman', 'local_cafe_outlined', 2, true),
  ('Obat', 'obat', 'local_pharmacy_outlined', 3, true),
  ('Herbal', 'herbal', 'spa_outlined', 4, true),
  ('Sembako', 'sembako', 'shopping_basket_outlined', 5, true)
on conflict (label) do update
set
  slug = excluded.slug,
  icon_name = excluded.icon_name,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();
update public.categories
set
  is_active = false,
  updated_at = now()
where label not in ('Makanan', 'Minuman', 'Obat', 'Herbal', 'Sembako');
insert into public.products (
  id,
  name,
  price,
  original_price,
  stock,
  claimed_percent,
  reward_points,
  badge,
  description,
  icon_name,
  tone_hex,
  image_url,
  category_labels,
  highlights,
  related_ids,
  sort_order,
  sku,
  barcode,
  slug,
  category_id,
  unit,
  brand,
  weight_grams,
  is_active
)
values
  (
    'mie_goreng_instan',
    'Mi Instan Goreng',
    3500,
    4000,
    180,
    82,
    2,
    'Favorit Harian',
    'Mi instan praktis untuk kebutuhan rumah tangga, warung, dan stok cepat saji anggota koperasi.',
    'restaurant_outlined',
    '#C55A11',
    null,
    array['Makanan'],
    array['Praktis dimasak', 'Harga hemat', 'Stok cepat', 'Cocok untuk warung'],
    array['biskuit_gandum', 'beras_premium_5kg'],
    1,
    'KDMP-MKN-001',
    '899000100001',
    'mi-instan-goreng',
    (select id from public.categories where label = 'Makanan'),
    'pcs',
    'KDMP Choice',
    85,
    true
  ),
  (
    'biskuit_gandum',
    'Biskuit Gandum',
    12500,
    14500,
    90,
    64,
    6,
    'Snack Keluarga',
    'Biskuit gandum renyah untuk camilan keluarga dan bekal perjalanan dengan kualitas yang konsisten.',
    'emoji_food_beverage_outlined',
    '#B17A35',
    null,
    array['Makanan'],
    array['Renyah', 'Kemasan praktis', 'Disukai keluarga', 'Cocok untuk bekal'],
    array['mie_goreng_instan', 'teh_melati_botol'],
    2,
    'KDMP-MKN-002',
    '899000100002',
    'biskuit-gandum',
    (select id from public.categories where label = 'Makanan'),
    'pcs',
    'KDMP Choice',
    220,
    true
  ),
  (
    'teh_melati_botol',
    'Teh Melati Botol',
    6500,
    7500,
    110,
    58,
    3,
    'Segar Dingin',
    'Minuman teh melati siap minum yang cocok untuk belanja harian dan konsumsi cepat.',
    'local_cafe_outlined',
    '#A63C3C',
    null,
    array['Minuman'],
    array['Siap minum', 'Rasa ringan', 'Segar', 'Mudah dibawa'],
    array['susu_uht_cokelat', 'kopi_gula_aren'],
    3,
    'KDMP-MNM-001',
    '899000200001',
    'teh-melati-botol',
    (select id from public.categories where label = 'Minuman'),
    'botol',
    'KDMP Refresh',
    350,
    true
  ),
  (
    'susu_uht_cokelat',
    'Susu UHT Cokelat 200ml',
    7800,
    9000,
    95,
    49,
    4,
    'Anak Sekolah',
    'Susu UHT rasa cokelat untuk konsumsi keluarga, sekolah, dan kebutuhan gizi harian.',
    'emoji_food_beverage_outlined',
    '#6C4A3A',
    null,
    array['Minuman'],
    array['Siap minum', 'Praktis', 'Disukai anak', 'Kemasan aman'],
    array['teh_melati_botol', 'biskuit_gandum'],
    4,
    'KDMP-MNM-002',
    '899000200002',
    'susu-uht-cokelat-200ml',
    (select id from public.categories where label = 'Minuman'),
    'kotak',
    'KDMP Fresh',
    200,
    true
  ),
  (
    'kopi_gula_aren',
    'Kopi Gula Aren',
    15000,
    17500,
    70,
    43,
    8,
    'UMKM Desa',
    'Kopi siap seduh dengan cita rasa gula aren yang cocok untuk kedai, rumah, dan tamu koperasi.',
    'coffee_outlined',
    '#5A3727',
    null,
    array['Minuman'],
    array['Aroma khas', 'Cocok untuk tamu', 'Produk UMKM', 'Mudah diseduh'],
    array['teh_melati_botol', 'madu_murni_250ml'],
    5,
    'KDMP-MNM-003',
    '899000200003',
    'kopi-gula-aren',
    (select id from public.categories where label = 'Minuman'),
    'sachet',
    'UMKM Binaan',
    25,
    true
  ),
  (
    'paracetamol_strip',
    'Paracetamol Strip',
    8500,
    10000,
    80,
    37,
    5,
    'Kebutuhan Dasar',
    'Obat penurun demam dan pereda nyeri ringan untuk kebutuhan kesehatan dasar keluarga.',
    'local_pharmacy_outlined',
    '#2E6F95',
    null,
    array['Obat'],
    array['Kemasan strip', 'Mudah disimpan', 'Kebutuhan dasar', 'Praktis'],
    array['oralit_sachet', 'madu_murni_250ml'],
    6,
    'KDMP-OBT-001',
    '899000300001',
    'paracetamol-strip',
    (select id from public.categories where label = 'Obat'),
    'strip',
    'KDMP Care',
    12,
    true
  ),
  (
    'oralit_sachet',
    'Oralit Sachet',
    4500,
    5500,
    120,
    29,
    2,
    'Siaga Rumah',
    'Larutan rehidrasi oral dalam sachet untuk pertolongan awal saat tubuh kehilangan cairan.',
    'local_pharmacy_outlined',
    '#4A90A4',
    null,
    array['Obat'],
    array['Sachet praktis', 'Mudah disimpan', 'Stok siaga', 'Harga terjangkau'],
    array['paracetamol_strip', 'jahe_merah_serbuk'],
    7,
    'KDMP-OBT-002',
    '899000300002',
    'oralit-sachet',
    (select id from public.categories where label = 'Obat'),
    'sachet',
    'KDMP Care',
    18,
    true
  ),
  (
    'madu_murni_250ml',
    'Madu Murni 250ml',
    48000,
    55000,
    45,
    54,
    10,
    'Produk Herbal',
    'Madu murni dari mitra binaan koperasi desa untuk konsumsi keluarga dan penunjang daya tahan tubuh.',
    'spa_outlined',
    '#A56A2A',
    null,
    array['Herbal'],
    array['Mitra desa', 'Rasa alami', 'Cocok harian', 'Produk herbal'],
    array['jahe_merah_serbuk', 'kopi_gula_aren'],
    8,
    'KDMP-HRB-001',
    '899000400001',
    'madu-murni-250ml',
    (select id from public.categories where label = 'Herbal'),
    'botol',
    'Herbal KDMP',
    250,
    true
  ),
  (
    'jahe_merah_serbuk',
    'Jahe Merah Serbuk',
    16000,
    18500,
    65,
    46,
    6,
    'Minuman Hangat',
    'Jahe merah serbuk untuk minuman hangat praktis dengan rasa kuat dan cocok untuk persediaan rumah.',
    'spa_outlined',
    '#9D4F24',
    null,
    array['Herbal'],
    array['Mudah diseduh', 'Rasa hangat', 'Stok rumah', 'Praktis'],
    array['madu_murni_250ml', 'oralit_sachet'],
    9,
    'KDMP-HRB-002',
    '899000400002',
    'jahe-merah-serbuk',
    (select id from public.categories where label = 'Herbal'),
    'sachet',
    'Herbal KDMP',
    150,
    true
  ),
  (
    'beras_premium_5kg',
    'Beras Premium 5kg',
    69000,
    76000,
    50,
    73,
    12,
    'Kebutuhan Pokok',
    'Beras premium dari pemasok koperasi yang cocok untuk kebutuhan keluarga dan warung makan.',
    'rice_bowl_rounded',
    '#B88A44',
    null,
    array['Sembako', 'Makanan'],
    array['Bulir utuh', 'Stok stabil', 'Pulen', 'Cocok untuk keluarga'],
    array['minyak_goreng_2l', 'gula_pasir_1kg'],
    10,
    'KDMP-SMB-001',
    '899000500001',
    'beras-premium-5kg',
    (select id from public.categories where label = 'Sembako'),
    'sak',
    'KDMP Pantry',
    5000,
    true
  ),
  (
    'minyak_goreng_2l',
    'Minyak Goreng 2L',
    34000,
    38000,
    75,
    61,
    7,
    'Stok Dapur',
    'Minyak goreng jernih untuk kebutuhan rumah tangga, usaha kecil, dan paket sembako cabang.',
    'water_drop_outlined',
    '#C89D28',
    null,
    array['Sembako'],
    array['Jernih', 'Harga stabil', 'Cocok untuk usaha', 'Stok rutin'],
    array['beras_premium_5kg', 'gula_pasir_1kg'],
    11,
    'KDMP-SMB-002',
    '899000500002',
    'minyak-goreng-2l',
    (select id from public.categories where label = 'Sembako'),
    'pouch',
    'KDMP Pantry',
    2000,
    true
  ),
  (
    'gula_pasir_1kg',
    'Gula Pasir 1kg',
    18000,
    20500,
    88,
    52,
    4,
    'Belanja Pokok',
    'Gula pasir untuk kebutuhan minuman, dapur rumah tangga, dan warung anggota koperasi.',
    'shopping_basket_outlined',
    '#E7D7A5',
    null,
    array['Sembako'],
    array['Kemasan 1kg', 'Harga bersaing', 'Stok aman', 'Kebutuhan harian'],
    array['beras_premium_5kg', 'teh_melati_botol'],
    12,
    'KDMP-SMB-003',
    '899000500003',
    'gula-pasir-1kg',
    (select id from public.categories where label = 'Sembako'),
    'pack',
    'KDMP Pantry',
    1000,
    true
  )
on conflict (id) do update
set
  name = excluded.name,
  price = excluded.price,
  original_price = excluded.original_price,
  stock = excluded.stock,
  claimed_percent = excluded.claimed_percent,
  reward_points = excluded.reward_points,
  badge = excluded.badge,
  description = excluded.description,
  icon_name = excluded.icon_name,
  tone_hex = excluded.tone_hex,
  image_url = excluded.image_url,
  category_labels = excluded.category_labels,
  highlights = excluded.highlights,
  related_ids = excluded.related_ids,
  sort_order = excluded.sort_order,
  sku = excluded.sku,
  barcode = excluded.barcode,
  slug = excluded.slug,
  category_id = excluded.category_id,
  unit = excluded.unit,
  brand = excluded.brand,
  weight_grams = excluded.weight_grams,
  is_active = excluded.is_active,
  updated_at = now();
update public.products
set
  is_active = false,
  updated_at = now()
where id not in (
  'mie_goreng_instan',
  'biskuit_gandum',
  'teh_melati_botol',
  'susu_uht_cokelat',
  'kopi_gula_aren',
  'paracetamol_strip',
  'oralit_sachet',
  'madu_murni_250ml',
  'jahe_merah_serbuk',
  'beras_premium_5kg',
  'minyak_goreng_2l',
  'gula_pasir_1kg'
);
